language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"

matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.0,<2.1"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install $DJANGO
  - pip install https://github.com/openwisp/django-netjsonconfig/tarball/master
  - pip install https://github.com/openwisp/openwisp-users/tarball/master
  - pip install -e .[users]
  - pip install -r requirements-test.txt

before_script:
  - ./runflake8
  - ./runisort

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=openwisp_utils runtests.py

after_success:
  coveralls
